from django.contrib import admin
from django.urls import path
from . import views
from accounts import views as acc_views
from django.contrib.auth import views as a_views
import posts.views as post_views

urlpatterns = [
    path('', views.index, name='index'),
    path('sitemap/',views.sitemaps,name="sitemap"),
    path('mleventsbu/',views.sbuform,name="mlevent"),
    path('aboutus', views.aboutus, name='aboutus'),
    path('resource/', views.reso, name='resources'),
    path('desc/', views.desc, name='desc'),
    path('datasnap/',views.datablog,name='datasnap'),
    path('getinvolved',views.contribute,name="getinvolved"),
    path('pricing/',views.price,name='price'),
    path('learner', views.learner, name='learner'),
    path('services', views.services, name='services'),
    path('projects', views.projects, name='projects'),
    path('tutorials', views.tutorials, name='tutorials'),
    path('careerpath', views.careerpath, name='careerpath'),
    path('404', views.error, name='404'),
    path('cookies', views.cookies, name='cookies'),
    path('privacy', views.privacy, name='privacy'),
    path('security', views.security, name='security'),
    path('terms', views.terms, name='terms'),
    path('design', views.design, name='design'),
    path('contact', views.contact, name='contact'),
    path('learnerstories', views.learnerstories, name='learnerstories'),
    path('ourpeople', views.ourpeople, name='ourpeople'),
    path('passwordgenerator', views.passwordgenerator, name='passwordgenerator'),
    path('qrcodegenerator', views.qrcodegenerator, name='qrcodegenerator'),
    path('version0', views.old, name='version0'),
    path('storage', views.storage, name='storage'),
    path('news/', views.tasks, name='news'),
    path('faq', views.FaqList.as_view(), name='faq'),
    path('community', views.community, name='community'),
    path('accessdenied', views.accessdenied, name='accessdenied'),
    path('path', views.path, name='path'),
    path('nextpage', views.nextpage, name='nextpage'),
    path('register', acc_views.RegistrationView.as_view(), name='register'),
    path('login/', acc_views.LoginView.as_view(), name='login'),
    path('logout/', acc_views.logout, name='logout'),
    path('activate/<uidb64>/<token>', acc_views.VerificationView.as_view(), name='activate'),
    path('reset_password/', a_views.PasswordResetView.as_view(template_name='password_reset.html'), name='reset_password'),
    path('reset_password_sent/', a_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', a_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'), name='password_reset_confirm'),
    path('reset_password_complete/', a_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), name='password_reset_complete'),
    path('<slug>/edit/', acc_views.update_profile, name='update'),
    path('<slug>/', acc_views.ShowProfile.as_view(), name='show_profile'),
    path('<slug>/dashboard/', acc_views.ShowDashboard.as_view(), name='dashboard'),
    path('<slug>/redeem/', acc_views.xp_redeem_cash, name='xp_redeem_cash'),
    path('<slug>/feed', post_views.feeds, name='feed'),
    path('<slug>/notifications', acc_views.notify, name='notifications'),
    path('<slug>/markread/', acc_views.mark_read, name='status'),
    path('<slug>/leaderboard',acc_views.leaderboard, name='leaderboard'),
    path('<slug>/accountsettings', acc_views.accountsettings, name='accountsettings'),
    path('<slug>/courses', acc_views.dashcourseListView.as_view(), name='dashcourses'),
    path('<slug>/careerpaths', acc_views.dashCareerListView.as_view(), name='dashcareerpaths'),
    path('<slug>/projects', acc_views.dashprojects, name='dashprojects'),
    path('<slug>/assesments', acc_views.dashassesments, name='dashassesments'),
    path('<slug>/topics', acc_views.topics, name='topics'),
    path('<slug>/events', acc_views.events, name='events'),
    path('update-skill/<str:delete>', acc_views.update_skill, name='update-skill'),
    path('update-lang/<str:delete>', acc_views.update_language, name='update-lang'),
    path('update-education/<str:slug>', acc_views.update_education, name='update-education'),
    path('update-proffesion/<str:slug>', acc_views.update_proffesion, name='update-proffesion'),
    path('post/reports-panel/', post_views.report_admin, name='report-panel'),
    path('post/<str:slug>/reports', post_views.post_reports, name='post-reports'),
]

