# Generated by Django 3.2.6 on 2022-12-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='hashtag name')),
                ('is_active', models.BooleanField(default=False)),
                ('followers', models.PositiveBigIntegerField(default=0, editable=False)),
                ('image', models.ImageField(upload_to='hashtag_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(choices=[('IP', 'Intellectual Property Violation'), ('VODO', 'Violence or Dangerous organizations'), ('BOH', 'Bullying or Harassment')], max_length=200)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashtags.hashtag')),
            ],
        ),
    ]
