# Generated by Django 3.2.6 on 2022-12-29 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashtag',
            name='permission_granted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permission_granted_by', to='auth.user'),
            preserve_default=False,
        ),
    ]
