# Generated by Django 3.2.6 on 2022-12-26 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_auto_20221130_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='followers',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='hashtag_images/'),
            preserve_default=False,
        ),
    ]
