# Generated by Django 3.2.6 on 2022-12-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0003_auto_20221226_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='description',
            field=models.TextField(default='defautl'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='followers',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
