# Generated by Django 3.2.6 on 2022-12-28 15:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('jobs_in', models.CharField(max_length=10, null=True)),
                ('salary', models.CharField(max_length=15, null=True)),
                ('learners', models.CharField(max_length=15, null=True)),
                ('banner_img', models.ImageField(upload_to='career')),
                ('bloglink', models.URLField(max_length=100)),
                ('webinar_link', models.URLField(max_length=100)),
                ('career_pdf', models.FileField(upload_to='career')),
                ('slug', models.CharField(editable=False, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='peopledescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_people_name', models.CharField(max_length=100)),
                ('desc_people_pic', models.ImageField(upload_to='career')),
                ('desc_people_from', models.CharField(max_length=100)),
                ('desc_people_desc', models.TextField(max_length=500)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peopledesc', to='careerpaths.careerpath')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_name', models.CharField(max_length=100)),
                ('people_pic', models.ImageField(upload_to='career')),
                ('people_from', models.ImageField(upload_to='career')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_people', to='careerpaths.careerpath')),
            ],
        ),
        migrations.CreateModel(
            name='Paths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(max_length=50)),
                ('path_description', models.TextField(max_length=300)),
                ('path_color', models.CharField(max_length=20)),
                ('path_icon', models.ImageField(upload_to='career')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('path_updated', models.DateField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths', to='careerpaths.careerpath')),
            ],
        ),
        migrations.CreateModel(
            name='lookingfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_pic', models.ImageField(upload_to='career')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peopledescription', to='careerpaths.careerpath')),
            ],
        ),
        migrations.CreateModel(
            name='Career_Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100)),
                ('lesson_description', models.CharField(max_length=500)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_lesson', to='careerpaths.careerpath')),
            ],
        ),
    ]
