# Generated by Django 3.2.6 on 2022-12-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='hashtags', to='hashtags.Hashtag'),
        ),
    ]
