# Generated by Django 3.2.6 on 2022-12-30 17:46

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_posts_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default=posts.models.generate_code_posts, editable=False, max_length=255),
        ),
    ]
