# Generated by Django 3.2.6 on 2021-09-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20210905_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(editable=False, max_length=100),
        ),
    ]
