# Generated by Django 3.2.6 on 2021-09-11 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_file_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='certificate_pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='certificate_pdf'),
            preserve_default=False,
        ),
    ]
