# Generated by Django 3.2.6 on 2022-12-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0003_alter_hashtag_permission_granted_by'),
        ('blogs', '0002_rename_tags_blogs_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='hashtags.Hashtag'),
        ),
    ]
