# Generated by Django 3.2.6 on 2022-12-28 15:35

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='course_pics')),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermidiate', 'Intermidiate'), ('Advanced', 'Advanced')], max_length=20)),
                ('cost', models.IntegerField(null=True)),
                ('gst', models.IntegerField(null=True)),
                ('total', models.IntegerField(editable=False, null=True)),
                ('release_status', models.BooleanField(default=False, null=True)),
                ('users', models.ManyToManyField(blank=True, related_name='course_profile', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('position', models.IntegerField()),
                ('resources', models.URLField(blank=True, max_length=1024, null=True)),
                ('min_time', models.IntegerField(default=1)),
                ('xp', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('min_time', models.IntegerField(blank=True, null=True)),
                ('num_lessons', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topics', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, default=0, null=True)),
                ('done', models.BooleanField(default=False)),
                ('courselesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lessons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_com_lessons', models.IntegerField(blank=True, default=0, null=True)),
                ('position', models.IntegerField(blank=True, default=0, null=True)),
                ('courselessons', models.ManyToManyField(blank=True, to='courses.UserLessons')),
                ('coursetopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(blank=True, related_name='user_courses', to='courses.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserCourses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lesson_resources')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_resources', to='courses.lessons')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_lessons', to='courses.topic'),
        ),
    ]
