# Generated by Django 3.2.6 on 2022-11-30 11:47

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('log', models.CharField(max_length=300)),
                ('amount', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=2, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('ph_num', models.CharField(blank=True, max_length=15, null=True)),
                ('skills', models.CharField(blank=True, max_length=400, null=True)),
                ('languages', models.CharField(blank=True, max_length=400, null=True)),
                ('default_coding_lang', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='profile_resumes')),
                ('institute_name', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_location', models.CharField(blank=True, max_length=100, null=True)),
                ('yearOfPassing', models.PositiveIntegerField(blank=True, default=2022, null=True, validators=[django.core.validators.MinValueValidator(1980), accounts.models.max_value_current_year])),
                ('current_cgpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('out_of', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('workExp', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('current_CTC', models.FloatField(blank=True, null=True)),
                ('notice_period', models.IntegerField(blank=True, null=True)),
                ('willing_to_relocate', models.BooleanField(blank=True, default=True, null=True)),
                ('expected_CTC', models.FloatField(blank=True, null=True)),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('dream_company', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('xp', models.IntegerField(blank=True, default=100, null=True)),
                ('techsnap_cash', models.IntegerField(blank=True, default=999, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True)),
                ('is_student', models.BooleanField(default=True)),
                ('is_creator', models.BooleanField(default=False)),
                ('is_hr', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(default=accounts.models.get_default_plan, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plans.plan')),
                ('teammates', models.ManyToManyField(blank=True, related_name='teammates', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proffesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=accounts.models.pro_generate_code, editable=False, max_length=20)),
                ('workExp', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('current_CTC', models.FloatField(blank=True, null=True)),
                ('notice_period', models.IntegerField(blank=True, null=True)),
                ('willing_to_relocate', models.BooleanField(blank=True, default=True, null=True)),
                ('expected_CTC', models.FloatField(blank=True, null=True)),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('dream_company', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notifications')),
                ('mark_as_read', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('url_name', models.CharField(blank=True, default='View', max_length=255, null=True)),
                ('notified_time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, max_length=16, null=True, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('logged_in', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=accounts.models.edu_generate_code, editable=False, max_length=20)),
                ('institute_name', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_location', models.CharField(blank=True, max_length=100, null=True)),
                ('yearOfPassing', models.PositiveIntegerField(blank=True, default=2022, null=True, validators=[django.core.validators.MinValueValidator(1980), accounts.models.max_value_current_year])),
                ('current_cgpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('out_of', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
