# Generated by Django 3.2.6 on 2022-11-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_auto_20221130_1515'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='hashtags.Hashtag'),
        ),
    ]
